---
title: "Heat or Eat"
author: "Phil Mike Jones"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
require("knitr")
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = TRUE
)
opts_knit$set(root.dir = normalizePath("../"))
old_digits <- options()[["digits"]]
options(digits = 2)
```

```{r resources}
library("heateat")
library("maptools"); library("rgeos")  # needed for fortify.sp()
library("ggplot2")
devtools::source_gist("d1f0aa148ac9fd1cf4b3")
```

```{r download-shapefiles}
# Download necessary shapefiles from census.ukdataservice.ac.uk
# LADs
if (!file.exists("data/shapes/lads.zip")) {
  message("Fetching shapefile(s)...")
  download.file(
    "https://census.edina.ac.uk/ukborders/easy_download/prebuilt/shape/England_lad_2011.zip",
    mode = "wb", method = "wget", destfile = "data/shapes/lads.zip"
  )
}

# LSOAs
if (!file.exists("data/shapes/lsoas.zip")) {
  message("Fetching shapefile(s)...")
  download.file(
    "https://census.edina.ac.uk/ukborders/easy_download/prebuilt/shape/England_lsoa_2011.zip",
    destfile = "data/shapes/lsoas.zip", method = "wget", mode = "wb"
  )
}

# Unzip...
if (!file.exists("data/shapes/lads/england_lad_2011_gen.shp")) {
  unzip("data/shapes/lads.zip",    exdir = "data/shapes/lads/")
}

if (!file.exists("data/shapes/lsoas/england_lsoa_2011_gen.shp")) {
  unzip("data/shapes/lsoas.zip",   exdir = "data/shapes/lsoa/")
}
```

```{r subset-lads, cache = TRUE}
# Load LADs
lads <- rgdal::readOGR(dsn = "data/shapes/lads", "england_lad_2011")
lads@data$label <- as.character(lads@data$label)

# Filter South Yorkshire
lads <- lads[lads@data$name == "Barnsley"  |
             lads@data$name == "Doncaster" |
             lads@data$name == "Rotherham" |
             lads@data$name == "Sheffield", ]
```

```{r clip-lsoas, cache = TRUE}
# LSOAs
lsoa <- rgdal::readOGR(dsn = "data/shapes/lsoa", "england_lsoa_2011")
lsoa@data$code <- as.character(lsoa@data$code)
lsoa_data <- lsoa@data

lsoa <- lsoa[lads, ]
lsoa <- rgeos::gIntersection(lads, lsoa, byid = TRUE, drop_lower_td = TRUE)

row.names(lsoa) <- gsub("9 ",   "", row.names(lsoa))
row.names(lsoa) <- gsub("214 ", "", row.names(lsoa))
row.names(lsoa) <- gsub("297 ", "", row.names(lsoa))
row.names(lsoa) <- gsub("320 ", "", row.names(lsoa))

lsoa <- sp::SpatialPolygonsDataFrame(lsoa,
  lsoa_data[row.names(lsoa_data) %in% row.names(lsoa), ])
lsoa@data$name <- as.character(lsoa@data$name)

conds <- all(grepl("Barnsley",  lsoa@data$name) |
             grepl("Doncaster", lsoa@data$name) |
             grepl("Rotherham", lsoa@data$name) |
             grepl("Sheffield", lsoa@data$name))
if (!conds) {
  warning("LSOA not joined correctly (LSOA not in South Yorkshire present)")
  stop()
}
```

```{r fuel-poverty, cache = TRUE}
# Load fuel poverty data
if (!file.exists("data/raw/fuel-poverty.xlsx")) {
  message("Obtaining fuel poverty data...")
  download.file("https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/485161/2013_Sub-regional_tables.xlsx",
                destfile = "data/raw/fuel-poverty.xlsx")
}

fp <- readxl::read_excel("data/raw/fuel-poverty.xlsx",
                         sheet = "Table 3", skip = 1, col_names = TRUE)
fp <- dplyr::select(fp, 1, 6, 7, 8)
fp <- na.omit(fp)
colnames(fp) <- c("code", "num_hh", "num_fph", "per_fph")

if (!(nrow(fp) == nrow(lsoa_data))) {
  warning("LSOA row numbers do not match")
  stop()
}
rm(lsoa_data)

# Join to shapefile
lsoa@data <- dplyr::inner_join(lsoa@data, fp, by = "code")
```

```{r create-maps, cache = TRUE}
# Fortify shapefiles
lads_f <- fortify(lads, region = "label")
lads_f <- dplyr::inner_join(lads_f, lads@data, by = c("id" = "label"))

lsoa_f <- fortify(lsoa, region = "code")
lsoa_f <- dplyr::inner_join(lsoa_f, lsoa@data, by = c("id" = "code"))
```

# Fuel poverty layers
```{r plot-lsoas, fig.width=7, fig.height=7}
ggplot() +
  geom_polygon(data = lsoa_f, aes(long, lat, group = group,
                                                    fill = per_fph),
                        colour = NA) +
  geom_polygon(data = lads_f, aes(long, lat, group = group),
                        fill = "transparent", colour = "black") +
  coord_equal() + mapl
```

```{r clean-up}
options(digits = old_digits)
```
